<?php
/**
 * Plumrocket Inc.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End-user License Agreement
 * that is available through the world-wide-web at this URL:
 * http://wiki.plumrocket.net/wiki/EULA
 * If you are unable to obtain it through the world-wide-web, please
 * send an email to support@plumrocket.com so we can send you a copy immediately.
 *
 * @package     Plumrocket RMA v2.x.x
 * @copyright   Copyright (c) 2017 Plumrocket Inc. (http://www.plumrocket.com)
 * @license     http://wiki.plumrocket.net/wiki/EULA  End-user License Agreement
 */
?>

<div class="returns-view prrma-instructions-buttons">

    <?php if ($block->hasPackingSlip()): ?>
        <a class="button action print-packing primary" href="<?php echo $block->getPackingSlipUrl() ?>" target="_blank">
            <span><?php echo __('Print Packing Slip') ?></span>
        </a>
    <?php endif ?>

    <?php if ($block->hasShippingLabel()): ?>
        <a class="button action print-shipping primary" href="<?php echo $block->getShippingLabelUrl() ?>" target="_blank" onclick="return popWinPrint(this.href)">
            <span><?php echo __('Print Shipping Label') ?></span>
        </a>
    <?php endif ?>

</div>