<?php
/**
 * Plumrocket Inc.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End-user License Agreement
 * that is available through the world-wide-web at this URL:
 * http://wiki.plumrocket.net/wiki/EULA
 * If you are unable to obtain it through the world-wide-web, please
 * send an email to support@plumrocket.com so we can send you a copy immediately.
 *
 * @package     Plumrocket RMA v2.x.x
 * @copyright   Copyright (c) 2017 Plumrocket Inc. (http://www.plumrocket.com)
 * @license     http://wiki.plumrocket.net/wiki/EULA  End-user License Agreement
 */
?>


<?php if ($block->showInstructions()): ?>
    <div id="returns_instructions_block" class="block">

        <div class="block-title">
            <strong><?php echo __('Return Instructions') ?></strong>
        </div>

        <div class="block-content">
            <?php echo $block->getInstructions() ?>

            <?php if (! $block->hasButtons()): ?>
                <div>
                    <?php echo $block->getChildHtml('buttons') ?>
                </div>
            <?php endif ?>
        </div>

    </div>
<?php endif ?>
